use_frameworks!

platform :ios, '9.0'

target 'FmaxTestAdvertisingSdk_Example' do
  pod 'FmaxTestAdvertisingSdk', :path => '../'

  target 'FmaxTestAdvertisingSdk_Tests' do
    inherit! :search_paths

    
  end
end
