# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FmaxTestAdvertisingSdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FmaxTestAdvertisingSdk
  pod 'Alamofire', '~>5.6.1'
  
  target 'FmaxTestAdvertisingSdkTests' do
    # Pods for testing
  end

end
